Update OrderServiceCICD.yml

diff --git a/.github/workflows/OrderServiceCICD.yml b/.github/workflows/OrderServiceCICD.yml
--- a/.github/workflows/OrderServiceCICD.yml
+++ b/.github/workflows/OrderServiceCICD.yml
@@ -15,87 +15,87 @@ env:
   SERVICE_NAME: orderservice
 
 jobs:
-  build-docker:
-    runs-on: ubuntu-latest
-    outputs:
-      version: ${{ steps.set-version.outputs.version }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # build-docker:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     version: ${{ steps.set-version.outputs.version }}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up JDK
-        uses: actions/setup-java@v4
-        with:
-          java-version: ${{ env.JAVA_VERSION }}
-          distribution: "temurin"
+  #     - name: Set up JDK
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         java-version: ${{ env.JAVA_VERSION }}
+  #         distribution: "temurin"
 
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
+  #     - name: Cache SonarCloud packages
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.sonar/cache
+  #         key: ${{ runner.os }}-sonar
+  #         restore-keys: ${{ runner.os }}-sonar
 
-      - name: Cache Maven packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
+  #     - name: Cache Maven packages
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.m2
+  #         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+  #         restore-keys: ${{ runner.os }}-m2
 
-      - name: Build & Analyze with SonarCloud
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # để Sonar comment vào PR
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          cd OrderService
-          mvn -B clean verify sonar:sonar -DskipTests \
-          -Dsonar.projectKey=Tam-Half_LearnMicrosevice \
-          -Dsonar.organization=tam-half \
-          -Dsonar.host.url=https://sonarcloud.io
+  #     - name: Build & Analyze with SonarCloud
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # để Sonar comment vào PR
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #       run: |
+  #         cd OrderService
+  #         mvn -B clean verify sonar:sonar -DskipTests \
+  #         -Dsonar.projectKey=Tam-Half_LearnMicrosevice \
+  #         -Dsonar.organization=tam-half \
+  #         -Dsonar.host.url=https://sonarcloud.io
 
   
 
-      - name: Build maven
-        id: maven-build
-        run: |
-          cd OrderService
-          mvn clean install -B -DskipTests > my_Log_Build.txt 2>&1
-          tail -n 10 my_Log_Build.txt
+  #     - name: Build maven
+  #       id: maven-build
+  #       run: |
+  #         cd OrderService
+  #         mvn clean install -B -DskipTests > my_Log_Build.txt 2>&1
+  #         tail -n 10 my_Log_Build.txt
           
     
 
-      - name: Check Maven Build Status
-        if: ${{ steps.maven-build.outcome != 'success' }} # Kiểm tra nếu Maven thất bại
-        run: |
-          echo "Maven build failed. Please check the logs above for details."
-          exit 1  # Dừng pipeline nếu Maven lỗi
+  #     - name: Check Maven Build Status
+  #       if: ${{ steps.maven-build.outcome != 'success' }} # Kiểm tra nếu Maven thất bại
+  #       run: |
+  #         echo "Maven build failed. Please check the logs above for details."
+  #         exit 1  # Dừng pipeline nếu Maven lỗi
 
-      - name: Set Version
-        id: set-version
-        run: |
-          echo "VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
+  #     - name: Set Version
+  #       id: set-version
+  #       run: |
+  #         echo "VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWD }}
+  #     - name: Login to Docker Hub
+  #       uses: docker/login-action@v2
+  #       with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_PASSWD }}
 
-      - name: Build Docker image
-        if: ${{ steps.maven-build.outcome == 'success' }}
-        run: |
-          cd OrderService
-          docker build -t ${{ secrets.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ steps.set-version.outputs.version }} .
+  #     - name: Build Docker image
+  #       if: ${{ steps.maven-build.outcome == 'success' }}
+  #       run: |
+  #         cd OrderService
+  #         docker build -t ${{ secrets.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ steps.set-version.outputs.version }} .
            
 
-      - name: Push Docker image to Docker Hub
-        run: |
-          docker push ${{ secrets.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ steps.set-version.outputs.version }}
+  #     - name: Push Docker image to Docker Hub
+  #       run: |
+  #         docker push ${{ secrets.REGISTRY }}/${{ env.SERVICE_NAME }}:${{ steps.set-version.outputs.version }}
           
   Config-k8s:
     runs-on: rancher-server
-    needs: [build-docker]
+    # needs: [build-docker]
     steps:
       - name: Configure Kubernetes
         run: |
@@ -108,7 +108,7 @@ jobs:
           
   Deploy-k8s:
     runs-on: rancher-server
-    needs: [build-docker, Config-k8s]
+    # needs: [build-docker, Config-k8s]
     steps:
       - name: Checkout Helm Charts
         uses: actions/checkout@v4
